import { convert } from './roman-numerals'

test('I is 1', () => expect(convert('I')).toBe(1))
test('V is 5', () => expect(convert('V')).toBe(5))
test('X is 10', () => expect(convert('X')).toBe(10))
test('L is 50', () => expect(convert('L')).toBe(50))
test('C is 100', () => expect(convert('C')).toBe(100))
test('D is 500', () => expect(convert('D')).toBe(500))
test('M is 1000', () => expect(convert('M')).toBe(1000))
test('II is 2', () => expect(convert('II')).toBe(2))
test('IV is 4', () => expect(convert('IV')).toBe(4))
test('IX is 9', () => expect(convert('IX')).toBe(9))
test('XL is 40', () => expect(convert('XL')).toBe(40))
test('XC is 90', () => expect(convert('XC')).toBe(90))
test('CD is 400', () => expect(convert('CD')).toBe(400))
test('CM is 900', () => expect(convert('CM')).toBe(900))
test('VII is 7', () => expect(convert('VII')).toBe(7))
test('IIII is invalid', () => expect(() => convert('IIII')).toThrowError())
test('IVX is invalid', () => expect(() => convert('IVX')).toThrowError())
test('A is invalid', () => expect(() => convert('A')).toThrowError())
