[tool.poetry]
name = "katas"
version = "0.1.0"
description = ""
authors = ["Luis Rodrigues <luis.rodrigues@springernature.com>"]

[tool.poetry.dependencies]
python = "^3.9"
pytest = "^6.2.4"
pytest-watch = "^4.2.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
